apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: p50lpxxyf-nodejs 
  janus-idp.io/tekton: p50lpxxyf-nodejs
  backstage.io/kubernetes-id: p50lpxxyf-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: p50lpxxyf-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml